%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%                                                                          %
%        Generated by MATLAB 8.1, MATLAB Coder 2.4 and HDL Coder 3.2      %
%                                                                          %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function [p1_out,p2_out] = vedge_wrapper_FixPt(b1_in,b2_in)
    fm = fimath( 'RoundingMethod', 'Floor', 'OverflowAction', 'Wrap', 'ProductMode', 'FullPrecision', 'MaxProductWordLength', 128, 'SumMode', 'FullPrecision', 'MaxSumWordLength', 128 );
    b1_in_in = fi( b1_in, 0, 8, 0, fm );
    b2_in_in = fi( b2_in, 0, 8, 0, fm );
    [p1_out_out,p2_out_out] = vedge_FixPt( b1_in_in, b2_in_in );
    p1_out = double( p1_out_out );
    p2_out = double( p2_out_out );
end
