%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%                                                                          %
%        Generated by MATLAB 8.1, MATLAB Coder 2.4 and HDL Coder 3.2      %
%                                                                          %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%#codegen
function [p1_out,p2_out] = vedge_FixPt(b1_in,b2_in)

fm = fimath('RoundingMethod', 'Floor', 'OverflowAction', 'Wrap', 'ProductMode', 'FullPrecision', 'MaxProductWordLength', 128, 'SumMode', 'FullPrecision', 'MaxSumWordLength', 128);
D = fi([ -1, 1 ]', 1, 3, 0, fm);
BSI = fi([ b1_in, b2_in ], 0, 8, 0, fm);
OrigImg_1 = fi(D*BSI, 1, 9, 0, fm);
%PD=abs((b1_in)-(b2_in));
p1_out = fi(OrigImg_1( 1, 1 ), 1, 9, 0, fm);
p2_out = fi(OrigImg_1( 2, 2 ), 0, 8, 0, fm);
end
